### ISSUE TITLE
Visao de Implementacao, qualidade e visao logica

### ISSUE THREAD

**Issue by GuilhermeBraz** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#104]
## Descrição
Criar os documentos de visao de Implementacao, qualidade e visao logica

## Critérios de Aceitação:
- Os tres documentos finalizados 

## Tarefas:
- [x] Visao de Implementacao
- [x] Qualidade
- [x] Visao logica

**Comment by AntonioAldisio** [comment]
Pessoal, lendo o documento  seria interessante colocar a introdução explicando o documento. Também é bom colocar links dentro do documento. Por fim, explicar melhor os exemplos abortados.
