### ISSUE TITLE
Refatoração dos diagramas do banco de dados 

### ISSUE THREAD

**Issue by AntonioAldisio** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#130]
## Descrição
Adicionar campos de foto no banco de dados para o prestador de serviço

## Critérios de Aceitação:
Obedecer 3FN

## Tarefas:
- [ ] DER
- [ ] DLD

**Comment by ArielSixwings** [comment]
![DERR-PosG](https://user-images.githubusercontent.com/38080649/161856012-7830d04a-8c56-43f3-9972-f87d2e78b81e.png)
![DLDR-PosG](https://user-images.githubusercontent.com/38080649/161856025-d39e919e-9702-419a-8d3c-db6613a8b09a.png)
