### ISSUE TITLE
Guia de estilo

### ISSUE THREAD

**Issue by joao15victor08** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#20]
## Descrição
Aqui a descrição da Issue

## Critérios de Aceitação:
Aqui critérios de aceitação 

## Tarefas:
- [x] Tarefa 1
- [x] Tarefa 2
- [x] Tarefa 3

**Comment by ArielSixwings** [comment]
Logo feita e paletas de cores selecionadas.
Tudo foi devidamente documentado e se encontra na wiki.
