### ISSUE TITLE
Definir tecnologias do back e front

### ISSUE THREAD

**Issue by joao15victor08** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#21]
## Descrição
Realizar votação para definir as tecnologias do Back e Front end.

## Critérios de Aceitação:
Ter sido realizado a reunião e as tecnologias terem sido devidamente definidas.

## Tarefas:
- [ ] Definir Tecnologias do Front-end
- [ ] Definir Tecnologias do Back-end

**Comment by Balbinoo** [comment]
![image](https://user-images.githubusercontent.com/54644626/152876655-4d2f403f-9d0b-410b-b832-2d3137b611bb.png)
