### ISSUE TITLE
Documentar Rich pictures

### ISSUE THREAD

**Issue by joao15victor08** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#4]
## Descrição
Documentar e juntar todos os rich picture produzidos

**Comment by joao15victor08** [comment]
![RIchPictureJobz_Joao](https://user-images.githubusercontent.com/32016154/151465281-c2d9d257-a4ad-4261-8343-0363f9c39440.png)

**Comment by Balbinoo** [comment]
![RichPicture](https://user-images.githubusercontent.com/54644626/151541430-54540977-9b0c-4be6-836f-171b425a29a6.png)

**Comment by ilus1** [comment]
![DiagramaIndividual](https://user-images.githubusercontent.com/71859307/151553107-bea5addd-c5af-4ae5-a074-df0c7e088f11.jpg)

**Comment by LorrayneCardozo** [comment]
![richPicture](https://user-images.githubusercontent.com/78423506/151560883-b4845127-14b3-40a4-be30-8ec7153cdcd5.png)

**Comment by GuilhermeBraz** [comment]
![image](https://user-images.githubusercontent.com/44117439/151568283-f238ed59-d984-4684-b702-60172153ea05.png)

**Comment by AlGouvea** [comment]
![Rich picture](https://user-images.githubusercontent.com/44756822/151572063-72980e23-e399-45f8-9079-67768b86fb95.jpg)

**Comment by Peh099** [comment]
![RichPicture_Pedro_Campos](https://user-images.githubusercontent.com/70337717/151578809-767d6469-5ee5-485d-876f-85d168306600.jpg)

**Comment by luis-furtado** [comment]
[Untitled Diagram.drawio.pdf](https://github.com/UnBArqDsw2021-2/2021.2_G6_Jobz_docs/files/7960950/Untitled.Diagram.drawio.pdf)

**Comment by luis-furtado** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/46112985/151601244-319da8be-c689-47db-95a8-100bcce27498.png)
