### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by LorrayneCardozo** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#67]
## Descrição
Criação do docker.

## Critérios de Aceitação:
O docker deve rodar corretamente na máquina de todos os integrantes.

## Tarefas:
- [x] Docker-Compose Front
- [x] Docker-Compose Back
- [x] MakeFile Front
- [x] MakeFile Back

**Comment by AntonioAldisio** [comment]
Atividade finalizada, talvez seja necessário algumas melhorias dos makefiles durante o desenvolvimento, mas se for preciso não será aberto outra issues.
