### ISSUE TITLE
BackEnd/US_CadastrodeServiço

### ISSUE THREAD

**Issue by Peh099** [UnBArqDsw2021-2/2021.2_G6_Jobz_docs#70]
## Descrição
Aqui a descrição da Issue

## Critérios de Aceitação:
Seguir ao máximo os modelos, se houver modificações, atualizar na modelagem. 
Conexão com o FrontEnd

## Tarefas:
- [x] Criação de models
- [x] CRUD funcional (POST/GET)

**Comment by ArielSixwings** [comment]
#Post da pagina

![post](https://user-images.githubusercontent.com/38080649/156897428-382ad7fa-9321-47ba-8240-dbbf368d35e0.png)

#Get da pagina.

![get](https://user-images.githubusercontent.com/38080649/156897377-0dee6cb2-a5be-4645-ac74-b60e27376b30.png)

#Banco de dados

![banco](https://user-images.githubusercontent.com/38080649/156897439-b08aa477-faa5-42c4-ba35-9544afada697.png)
.
